module.exports = [
  {
    id: 1,
    user_id: 23,
    user_name: "sherrie",
    created_at: "2023-11-08 09:59:36",
    content:
      "Serve it up: The art of a powerful tennis serve. Tips and tricks for acing your game!",
    sports_type: "tennis",
    likes_count: 225,
    comments_count: 111,
    replies_count: 74,
    Mentions: "@User1078",
  },
  {
    id: 2,
    user_id: 24,
    user_name: "uglyYute",
    created_at: "2023-11-17 11:16:36",
    content: "Disappointed with the referee's decision in today's game.",
    sports_type: "football",
    likes_count: 378,
    comments_count: 139,
    replies_count: 32,
    Mentions: "@User1022",
  },
  {
    id: 3,
    user_id: 25,
    user_name: "meetbilly_",
    created_at: "2023-10-27 19:48:36",
    content:
      "Game, set, match! What's your favorite tennis match of all time and why?",
    sports_type: "tennis",
    likes_count: 177,
    comments_count: 16,
    replies_count: 11,
    Mentions: "@User1057",
  },
  {
    id: 4,
    user_id: 22,
    user_name: "bamiee",
    created_at: "2023-11-02 23:37:36",
    content:
      "Goal celebrations: What's your favorite iconic football goal celebration of all time?",
    sports_type: "football",
    likes_count: 209,
    comments_count: 41,
    replies_count: 9,
    Mentions: "@User1008",
  },
  {
    id: 5,
    user_id: 21,
    user_name: "sweetnessoyin",
    created_at: "2023-11-18 15:28:36",
    content:
      "From street to stadium: The inspiring journey of football legends from humble beginnings.",
    sports_type: "football",
    likes_count: 241,
    comments_count: 151,
    replies_count: 10,
    Mentions: "@User1048",
  },
  {
    id: 6,
    user_id: 20,
    user_name: "mz_fiyin",
    created_at: "2023-11-03 05:33:36",
    content:
      "Transfer news is getting interesting. Who should we sign? Tactical evolution: How football formations have changed over the decades.",
    sports_type: "football",
    likes_count: 383,
    comments_count: 14,
    replies_count: 71,
    Mentions: "@User1079",
  },
  {
    id: 7,
    user_id: 19,
    user_name: "mz_winnie",
    created_at: "2023-11-12 23:17:36",
    content:
      "Golden boot race: Predictions for the top goal-scorer in the upcoming football season.",
    sports_type: "football",
    likes_count: 346,
    comments_count: 169,
    replies_count: 23,
    Mentions: "@User1092",
  },
  {
    id: 8,
    user_id: 18,
    user_name: "perlita_bng",
    created_at: "2023-11-10 19:00:36",
    content:
      "Football and culture: How the sport has become a global phenomenon that transcends borders.",
    sports_type: "football",
    likes_count: 129,
    comments_count: 96,
    replies_count: 84,
    Mentions: "@User1029",
  },
  {
    id: 9,
    user_id: 17,
    user_name: "sophia",
    created_at: "2023-11-04 01:48:36",
    content:
      "The slice backhand: A subtle yet powerful weapon in the tennis arsenal. Mastering the technique!",
    sports_type: "tennis",
    likes_count: 458,
    comments_count: 194,
    replies_count: 89,
    Mentions: "@User1065",
  },
  {
    id: 10,
    user_id: 15,
    user_name: "neeran",
    created_at: "2023-11-14 05:36:36",
    content:
      "Football fashion: Ranking the most stylish football kits of the season.",
    sports_type: "football",
    likes_count: 367,
    comments_count: 20,
    replies_count: 7,
    Mentions: "@User1096",
  },
  {
    id: 11,
    user_id: 16,
    user_name: "bundey",
    created_at: "2023-11-02 18:47:36",
    content:
      "Net play strategies: How to dominate the net and control the point.",
    sports_type: "tennis",
    likes_count: 16,
    comments_count: 188,
    replies_count: 57,
    Mentions: "@User1050",
  },
  {
    id: 12,
    user_id: 14,
    user_name: "casino",
    created_at: "2023-10-27 07:34:36",
    content:
      "VAR controversies: Discussing the impact of Video Assistant Referee in modern football.",
    sports_type: "football",
    likes_count: 182,
    comments_count: 177,
    replies_count: 6,
    Mentions: "@User1006",
  },
  {
    id: 13,
    user_id: 13,
    user_name: "themaing",
    created_at: "2023-11-12 13:27:36",
    content:
      "Tennis fashion through the years: From wooden rackets to high-tech gear. Evolution in style!",
    sports_type: "tennis",
    likes_count: 460,
    comments_count: 81,
    replies_count: 92,
    Mentions: "@User1087",
  },
  {
    id: 14,
    user_id: 12,
    user_name: "awillo",
    created_at: "2023-10-30 19:59:36",
    content:
      "Football trivia: Lesser-known facts about the beautiful game. Test your knowledge!",
    sports_type: "football",
    likes_count: 64,
    comments_count: 172,
    replies_count: 63,
    Mentions: "@User1091",
  },
  {
    id: 15,
    user_id: 10,
    user_name: "Tomato",
    created_at: "2023-10-24 18:16:36",
    content:
      "Captains of the pitch: Analyzing the leadership styles of football team captains.",
    sports_type: "football",
    likes_count: 48,
    comments_count: 70,
    replies_count: 3,
    Mentions: "@User1",
  },
  {
    id: 16,
    user_id: 3,
    user_name: "blackandfly",
    created_at: "2023-10-22 19:02:36",
    content:
      "Football rivalries: The most intense and historic clashes in the world of football.",
    sports_type: "football",
    likes_count: 356,
    comments_count: 155,
    replies_count: 57,
    Mentions: "@User1032",
  },
  {
    id: 17,
    user_id: 9,
    user_name: "coyesanya",
    created_at: "2023-11-13 09:04:36",
    content:
      "The mental game: Staying focused and composed on the tennis court. Mind over matter!",
    sports_type: "tennis",
    likes_count: 101,
    comments_count: 112,
    replies_count: 87,
    Mentions: "@User1005",
  },
  {
    id: 18,
    user_id: 11,
    user_name: "machado",
    created_at: "2023-11-13 15:47:36",
    content:
      "Youth academies: The breeding grounds for future football superstars. Which club has the best?",
    sports_type: "football",
    likes_count: 395,
    comments_count: 38,
    replies_count: 16,
    Mentions: "@User1012",
  },
  {
    id: 19,
    user_id: 8,
    user_name: "isawtobi",
    created_at: "2023-10-28 00:17:36",
    content:
      "Clay, grass, or hard court? Which surface suits your playing style best?",
    sports_type: "tennis",
    likes_count: 355,
    comments_count: 150,
    replies_count: 74,
    Mentions: "@User1013",
  },
  {
    id: 20,
    user_id: 6,
    user_name: "mc_fish",
    created_at: "2023-10-22 11:30:36",
    content: "Celebrating our club's historic win!",
    sports_type: "football",
    likes_count: 139,
    comments_count: 23,
    replies_count: 73,
    Mentions: "@User1073",
  },
  {
    id: 21,
    user_id: 7,
    user_name: "timigod",
    created_at: "2023-11-14 13:36:36",
    content:
      "Grand Slam moments: Memorable upsets in tennis history. Which one shocked you the most?",
    sports_type: "tennis",
    likes_count: 151,
    comments_count: 10,
    replies_count: 84,
    Mentions: "@User1010",
  },
  {
    id: 22,
    user_id: 4,
    user_name: "manlikecaster",
    created_at: "2023-11-03 00:03:36",
    content: "Great game last night! What a win for our team!",
    sports_type: "football",
    likes_count: 368,
    comments_count: 102,
    replies_count: 72,
    Mentions: "@User1016",
  },
  {
    id: 23,
    user_id: 5,
    user_name: "blueflame",
    created_at: "2023-10-20 05:10:36",
    content:
      "Doubles dynamics: Communication and teamwork essentials for a winning partnership.",
    sports_type: "tennis",
    likes_count: 262,
    comments_count: 140,
    replies_count: 14,
    Mentions: "@User1076",
  },
  {
    id: 24,
    user_id: 1,
    user_name: "maaziMide",
    created_at: "2023-10-25 19:34:36",
    content: "Looking forward to the big match this weekend. Predictions?",
    sports_type: "football",
    likes_count: 338,
    comments_count: 175,
    replies_count: 29,
    Mentions: "@User1015",
  },
  {
    id: 25,
    user_id: 2,
    user_name: "pelumi",
    created_at: "2023-10-21 21:45:36",
    content:
      "Tennis fitness drills: Off-court exercises to improve your on-court performance.",
    sports_type: "tennis",
    likes_count: 313,
    comments_count: 25,
    replies_count: 70,
    Mentions: "@User1012",
  },
  {
    id: 26,
    user_id: 24,
    user_name: "uglyYute",
    created_at: "2023-11-01 17:38:36",
    content:
      "The goalkeeper's perspective: Insights into the high-pressure role between the goalposts.",
    sports_type: "football",
    likes_count: 397,
    comments_count: 47,
    replies_count: 33,
    Mentions: "@User1022",
  },
  {
    id: 27,
    user_id: 25,
    user_name: "meetbilly_",
    created_at: "2023-11-17 04:30:36",
    content:
      "Tennis technology: How innovations like Hawkeye and smart rackets are changing the game.",
    sports_type: "tennis",
    likes_count: 100,
    comments_count: 108,
    replies_count: 11,
    Mentions: "@User1084",
  },
  {
    id: 28,
    user_id: 20,
    user_name: "mz_fiyin",
    created_at: "2023-11-11 06:50:36",
    content:
      "Football and philanthropy: How players contribute to charitable causes off the field.",
    sports_type: "football",
    likes_count: 235,
    comments_count: 59,
    replies_count: 56,
    Mentions: "@User1100",
  },
  {
    id: 29,
    user_id: 23,
    user_name: "sherrie",
    created_at: "2023-10-22 15:44:36",
    content:
      "The rise of young talent: Next-gen players making waves in professional tennis.",
    sports_type: "tennis",
    likes_count: 276,
    comments_count: 172,
    replies_count: 44,
    Mentions: "@User1052",
  },
  {
    id: 30,
    user_id: 19,
    user_name: "mz_winnie",
    created_at: "2023-11-04 18:23:36",
    content:
      "Football fitness: Behind-the-scenes training routines to keep players in peak condition.",
    sports_type: "football",
    likes_count: 346,
    comments_count: 28,
    replies_count: 70,
    Mentions: "@User1055",
  },
  {
    id: 31,
    user_id: 22,
    user_name: "bamiee",
    created_at: "2023-10-20 04:03:36",
    content:
      "Stunning comeback in the second set! The lob shot: A tactical move to outsmart your opponent. When and how to use it! #tennislove",
    sports_type: "tennis",
    likes_count: 260,
    comments_count: 20,
    replies_count: 86,
    Mentions: "@User1093",
  },
  {
    id: 32,
    user_id: 21,
    user_name: "sweetnessoyin",
    created_at: "2023-10-21 02:33:36",
    content:
      "Football documentaries: Dive into the untold stories of the beautiful game.",
    sports_type: "football",
    likes_count: 95,
    comments_count: 18,
    replies_count: 28,
    Mentions: "@User1077",
  },
  {
    id: 33,
    user_id: 17,
    user_name: "sophia",
    created_at: "2023-11-10 09:43:36",
    content:
      "Injury prevention in tennis: Strengthening exercises to keep you on the court.",
    sports_type: "tennis",
    likes_count: 173,
    comments_count: 113,
    replies_count: 5,
    Mentions: "@User1047",
  },
  {
    id: 34,
    user_id: 18,
    user_name: "perlita_bng",
    created_at: "2023-11-03 22:43:36",
    content:
      "Football's greatest upsets: Recalling the underdog victories that stunned the world.",
    sports_type: "football",
    likes_count: 452,
    comments_count: 85,
    replies_count: 85,
    Mentions: "@User1057",
  },
  {
    id: 35,
    user_id: 3,
    user_name: "blackandfly",
    created_at: "2023-11-13 07:00:36",
    content:
      "Tennis superstitions: Do you have any pre-match rituals or lucky charms",
    sports_type: "tennis",
    likes_count: 100,
    comments_count: 46,
    replies_count: 98,
    Mentions: "@User1047",
  },
  {
    id: 36,
    user_id: 15,
    user_name: "neeran",
    created_at: "2023-11-10 12:07:36",
    content:
      "Free-kick mastery: Examining the technique and precision behind the perfect free-kick.",
    sports_type: "football",
    likes_count: 120,
    comments_count: 97,
    replies_count: 68,
    Mentions: "@User1085",
  },
  {
    id: 37,
    user_id: 16,
    user_name: "bundey",
    created_at: "2023-10-25 16:50:36",
    content:
      "Tennis legends: Comparing eras – who would win in a match between Federer and Sampras?",
    sports_type: "tennis",
    likes_count: 189,
    comments_count: 162,
    replies_count: 45,
    Mentions: "@User1003",
  },
  {
    id: 38,
    user_id: 14,
    user_name: "casino",
    created_at: "2023-11-10 22:03:36",
    content:
      "Football and technology: How innovations like goal-line technology have changed the game.",
    sports_type: "football",
    likes_count: 3,
    comments_count: 145,
    replies_count: 5,
    Mentions: "@User1065",
  },
  {
    id: 39,
    user_id: 13,
    user_name: "themaing",
    created_at: "2023-11-03 19:52:36",
    content:
      "Tennis etiquette: The do's and don'ts of sportsmanship on the court.",
    sports_type: "tennis",
    likes_count: 248,
    comments_count: 196,
    replies_count: 23,
    Mentions: "@User1002",
  },
  {
    id: 40,
    user_id: 12,
    user_name: "awillo",
    created_at: "2023-10-19 19:38:36",
    content:
      "The rise of women's football: Celebrating the growth and success of women in the sport.",
    sports_type: "football",
    likes_count: 186,
    comments_count: 168,
    replies_count: 71,
    Mentions: "@User1070",
  },
  {
    id: 41,
    user_id: 10,
    user_name: "Tomato",
    created_at: "2023-10-20 03:32:36",
    content:
      "What an incredible match at the Open today! Game analysis: Breaking down epic rallies and understanding strategy.",
    sports_type: "tennis",
    likes_count: 436,
    comments_count: 129,
    replies_count: 43,
    Mentions: "@User1004",
  },
  {
    id: 42,
    user_id: 11,
    user_name: "machado",
    created_at: "2023-11-09 00:54:36",
    content:
      "Football superstitions: Strange rituals and beliefs of players before a big match.",
    sports_type: "football",
    likes_count: 364,
    comments_count: 174,
    replies_count: 13,
    Mentions: "@User1083",
  },
  {
    id: 43,
    user_id: 9,
    user_name: "coyesanya",
    created_at: "2023-10-20 16:29:36",
    content:
      "The art of the drop shot: Surprise your opponent and seize control of the point!",
    sports_type: "tennis",
    likes_count: 110,
    comments_count: 62,
    replies_count: 27,
    Mentions: "@User1040",
  },
  {
    id: 44,
    user_id: 8,
    user_name: "isawtobi",
    created_at: "2023-11-17 10:20:36",
    content:
      "Football and politics: Examining the intersection of the sport with global socio-political issues.",
    sports_type: "football",
    likes_count: 85,
    comments_count: 142,
    replies_count: 57,
    Mentions: "@User1018",
  },
  {
    id: 45,
    user_id: 1,
    user_name: "maaziMide",
    created_at: "2023-11-06 02:58:36",
    content:
      "The serve-and-volley comeback: Is this classic strategy making a return to the game?",
    sports_type: "tennis",
    likes_count: 285,
    comments_count: 111,
    replies_count: 22,
    Mentions: "@User1002",
  },
  {
    id: 46,
    user_id: 6,
    user_name: "mc_fish",
    created_at: "2023-10-31 16:56:36",
    content:
      "Football in art: Iconic football moments immortalized through paintings and sculptures.",
    sports_type: "football",
    likes_count: 132,
    comments_count: 149,
    replies_count: 85,
    Mentions: "@User1039",
  },
  {
    id: 47,
    user_id: 7,
    user_name: "timigod",
    created_at: "2023-10-29 17:40:36",
    content:
      "Tennis and mindfulness: The role of meditation in improving concentration and focus on the court.",
    sports_type: "tennis",
    likes_count: 73,
    comments_count: 21,
    replies_count: 98,
    Mentions: "@User1051",
  },
  {
    id: 48,
    user_id: 4,
    user_name: "manlikecaster",
    created_at: "2023-10-24 12:03:36",
    content:
      "Football in cinema: Must-watch movies capturing the drama and passion of the sport.",
    sports_type: "football",
    likes_count: 308,
    comments_count: 103,
    replies_count: 88,
    Mentions: "@User1053",
  },
  {
    id: 49,
    user_id: 3,
    user_name: "blackandfly",
    created_at: "2023-10-19 18:36:36",
    content:
      "Excited for the upcoming grand slam. Tennis travel: Must-visit destinations for tennis enthusiasts around the world.",
    sports_type: "tennis",
    likes_count: 379,
    comments_count: 183,
    replies_count: 40,
    Mentions: "@User1020",
  },
  {
    id: 50,
    user_id: 25,
    user_name: "meetbilly_",
    created_at: "2023-11-08 15:20:36",
    content:
      "Football and music: The anthems and songs that define the spirit of the game.",
    sports_type: "football",
    likes_count: 113,
    comments_count: 46,
    replies_count: 34,
    Mentions: "@User1023",
  },
];
