module.exports = [
  {
    id: 1,
    username: "MaaziMide",
    full_name: "Olumide Jegede",
    bio: "Sports enthusiast",
    tennis: true,
    football: true,
    email: "olumide@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 2,
    username: "Pelumi",
    full_name: "Oyin Jegede",
    bio: "Sports enthusiast",
    tennis: true,
    email: "oyin@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 3,
    username: "Blackandfly",
    full_name: "Moses Maaji",
    bio: "Sports enthusiast",
    tennis: true,
    football: true,
    email: "moses@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 4,
    username: "Manlikecaster",
    full_name: "Paul Semenya",
    bio: "Sports enthusiast",
    tennis: true,
    football: true,
    email: "paul@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 5,
    username: "Blueflame",
    full_name: "Ifedoyin Shotunde",
    bio: "Sports enthusiast",
    tennis: true,
    football: true,
    email: "ife@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 6,
    username: "Mc_fish",
    full_name: "Abdul Mahmud",
    bio: "Sports enthusiast",
    tennis: true,
    football: true,
    email: "abdul@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 7,
    username: "Timigod",
    full_name: "Timi Ajiboye",
    bio: "Sports enthusiast",
    tennis: true,
    email: "timi@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 8,
    username: "Isawtobi",
    full_name: "Tobi Isola",
    bio: "Sports enthusiast",
    tennis: true,
    football: true,
    email: "tobi@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "tobi",
  },
  {
    id: 9,
    username: "Coyesanya",
    full_name: "Caroline Oyesanya",
    bio: "Sports enthusiast",
    tennis: true,
    football: true,
    email: "caroline@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "caroline",
  },
  {
    id: 10,
    username: "Tomato",
    full_name: "Tomi Akanni",
    bio: "Sports enthusiast",
    tennis: true,
    football: true,
    email: "tomi@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 11,
    username: "Machado",
    full_name: "Alayo Machado",
    bio: "Sports enthusiast",
    football: true,
    email: "alayo@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 12,
    username: "Awillo",
    full_name: "Williams Ogah",
    bio: "Sports enthusiast",
    football: true,
    email: "willo@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 13,
    username: "Themaing",
    full_name: "Dimeji A",
    bio: "Sports enthusiast",
    tennis: true,
    football: true,
    email: "dimeji@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 14,
    username: "Casino",
    full_name: "Chukwunyem Anumundu",
    bio: "Sports enthusiast",
    football: true,
    email: "cas@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 15,
    username: "Neeran",
    full_name: "Olaniran Awosika",
    bio: "Sports enthusiast",
    tennis: true,
    football: true,
    email: "niran@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 16,
    username: "Ifebusola_",
    full_name: "Ifebusola Shotunde",
    bio: "Sports enthusiast",
    tennis: true,
    email: "busola@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 17,
    username: "Sophia_",
    full_name: "Sofia Gagliano",
    bio: "Sports enthusiast",
    tennis: true,
    email: "sofia@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 18,
    username: "Perlita_bng",
    full_name: "Pearl Boateng",
    bio: "Sports enthusiast",
    football: true,
    email: "pearl@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 19,
    username: "Mz_Winnie",
    full_name: "Winnie Ishiekwene",
    bio: "Sports enthusiast",
    tennis: true,
    football: true,
    email: "winnie@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 20,
    username: "Ms_Fiyin",
    full_name: "Fiyin Nasiru",
    bio: "Sports enthusiast",
    football: true,
    email: "fiyin@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 21,
    username: "Sweetnessoyin",
    full_name: "Oyin Jongbo",
    bio: "Sports enthusiast",
    tennis: true,
    football: true,
    email: "oyinj@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 22,
    username: "Bamiee",
    full_name: "Ayobami H.",
    bio: "Sports enthusiast",
    tennis: true,
    email: "bami@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 23,
    username: "Sherrie",
    full_name: "Sherry Malomo",
    bio: "Sports enthusiast",
    tennis: true,
    email: "sheri@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 24,
    username: "UglyYute",
    full_name: "Segun Erin",
    bio: "Sports enthusiast",
    football: true,
    email: "segun@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "loremipsum",
  },
  {
    id: 25,
    username: "Meetbilly_",
    full_name: "Billy Jegede",
    bio: "Sports enthusiast",
    tennis: true,
    football: true,
    email: "billy@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "meetbilly",
  },
];
