module.exports = [
  {
    id: 1,
    username: "maaziMide",
    full_name: "Olumide Jegede",
    bio: "Sports enthusiast",
    sports_type: "Tennis, Football",
    email: "olumide@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 2,
    username: "pelumi",
    full_name: "Oyin Jegede",
    bio: "Sports enthusiast",
    sports_type: "Tennis",
    email: "oyin@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 3,
    username: "blackandfly",
    full_name: "Moses Maaji",
    bio: "Sports enthusiast",
    sports_type: "Tennis, Football",
    email: "moses@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 4,
    username: "manlikecaster",
    full_name: "Paul Semenya",
    bio: "Sports enthusiast",
    sports_type: "Tennis, Football",
    email: "paul@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 5,
    username: "blueflame",
    full_name: "Ifedoyin Shotunde",
    bio: "Sports enthusiast",
    sports_type: "Tennis, Football",
    email: "ife@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 6,
    username: "mc_fish",
    full_name: "Abdul Mahmud",
    bio: "Sports enthusiast",
    sports_type: "Tennis, Football",
    email: "abdul@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 7,
    username: "timigod",
    full_name: "Timi Ajiboye",
    bio: "Sports enthusiast",
    sports_type: "Tennis",
    email: "timi@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 8,
    username: "isawtobi",
    full_name: "Tobi Isola",
    bio: "Sports enthusiast",
    sports_type: "Tennis, Football",
    email: "tobi@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 9,
    username: "coyesanya",
    full_name: "Caroline Oyesanya",
    bio: "Sports enthusiast",
    sports_type: "Tennis, Football",
    email: "caroline@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 10,
    username: "Tomato",
    full_name: "Tomi Akanni",
    bio: "Sports enthusiast",
    sports_type: "Tennis, Football",
    email: "tomi@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 11,
    username: "machado",
    full_name: "Alayo Mach",
    bio: "Sports enthusiast",
    sports_type: "Football",
    email: "alayo@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 12,
    username: "awillo",
    full_name: "Williams Ogah",
    bio: "Sports enthusiast",
    sports_type: "Football",
    email: "willo@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 13,
    username: "themaing",
    full_name: "Dimeji A",
    bio: "Sports enthusiast",
    sports_type: "Tennis, Football",
    email: "dimeji@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 14,
    username: "casino",
    full_name: "Chukwunyem Anu",
    bio: "Sports enthusiast",
    sports_type: "Football",
    email: "cas@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 15,
    username: "neeran",
    full_name: "Olaniran Awo",
    bio: "Sports enthusiast",
    sports_type: "Tennis, Football",
    email: "niran@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 16,
    username: "bundey",
    full_name: "Ifebusola Sho",
    bio: "Sports enthusiast",
    sports_type: "Tennis",
    email: "busola@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 17,
    username: "sophia",
    full_name: "Sofia Gag",
    bio: "Sports enthusiast",
    sports_type: "Tennis",
    email: "sofia@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 18,
    username: "perlita_bng",
    full_name: "Pearl Boateng",
    bio: "Sports enthusiast",
    sports_type: "Football",
    email: "pearl@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 19,
    username: "mz_winnie",
    full_name: "Winnie Ishiekwene",
    bio: "Sports enthusiast",
    sports_type: "Tennis, Football",
    email: "winnie@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 20,
    username: "mz_fiyin",
    full_name: "Fiyin Nasiru",
    bio: "Sports enthusiast",
    sports_type: "Football",
    email: "fiyin@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 21,
    username: "sweetnessoyin",
    full_name: "Oyin Jongbo",
    bio: "Sports enthusiast",
    sports_type: "Tennis, Football",
    email: "oyinj@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 22,
    username: "bamiee",
    full_name: "Ayobami H.",
    bio: "Sports enthusiast",
    sports_type: "Tennis",
    email: "bami@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 23,
    username: "sherrie",
    full_name: "Sherry Malz",
    bio: "Sports enthusiast",
    sports_type: "Tennis",
    email: "sheri@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/5756481/pexels-photo-5756481.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 24,
    username: "uglyYute",
    full_name: "Segun Erin",
    bio: "Sports enthusiast",
    sports_type: "Football",
    email: "segun@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
  {
    id: 25,
    username: "meetbilly_",
    full_name: "Billy Jegede",
    bio: "Sports enthusiast",
    sports_type: "Tennis, Football",
    email: "billy@test.com",
    profile_image_url:
      "https://images.pexels.com/photos/17547506/pexels-photo-17547506/free-photo-of-silhouette-of-a-man-in-a-cap.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    password: "lorem ipsum",
  },
];
